records:
  # The hostname record to update in Route53
  your-hostname.net:
    # ZoneID for the hosted zone
    zoneId: "example-zone-id"
    # TTL of the record, in seconds.
    ttl: 300
    # Any additional hosts, within the same hosted zone,
    # that should also be updated as well.
    additionalHosts:
      - "additional-host.your-hostname.net"

pushover:
  api-token: "pushover-app-api-token"
  user-key: "your-pushover-user-key"
